version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - run:
          command: rm -rf node_modules && npm i
          when: on_fail
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: |
          EXT_VERSION=$(grep -oP "(?<=version\": \").*(?=\")" package.json)
          echo "export EXT_VERSION=${EXT_VERSION}" >> $BASH_ENV
          sed -i "s/1.0.0/${EXT_VERSION}/g" ext/manifest.json
      - run: cd ext && zip -r ../deploy.zip *
      - run: |
          ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T deploy.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
      - run: 'node deploy/firefox.js ext artifacts ${AMO_KEY} ${AMO_SECRET} ${AMO_EXT_ID} ${EXT_VERSION}'
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master