name: Deploy workflow
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: npm ci
    
    - name: Install web-ext
      run: sudo npm i -g web-ext
    
    - name: Build
      run: npm run build
    
    - name: Set extension version
      run: |
        EXT_VERSION=$(grep -oP "(?<=version\": \").*(?=\")" package.json)        
        sed -i "s/1.0.0/${EXT_VERSION}/g" ext/manifest.json
        echo "EXT_VERSION=${EXT_VERSION}" >> $GITHUB_ENV
            
    - name: Zip package
      run: |
        cd ext/
        web-ext build
            
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.EXT_VERSION }}
        release_name: ${{ env.EXT_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ext/web-ext-artifacts/genesyx_game_helper-${{ env.EXT_VERSION }}.zip
        asset_name: genesyx_game_helper-${{ env.EXT_VERSION }}.zip
        asset_content_type: application/zip
    
    - name: Upload package to Mozilla Firefox
      run: |
        cd ext/
        web-ext sign --api-key=${{ secrets.AMO_JWT_ISSUER }} --api-secret=${{ secrets.AMO_JWT_SECRET }}
      continue-on-error: true
        
    - name: Upload package to Google Chrome
      run: |
        cd ext/web-ext-artifacts/
        ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${{ secrets.GOOGLE_CLIENT_ID }}&client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }}&refresh_token=${{ secrets.GOOGLE_REFRESH_TOKEN }}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
        curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T genesyx_game_helper-${{ env.EXT_VERSION }}.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ secrets.GOOGLE_EXTENSION_APP_ID }}"
        curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${{ secrets.GOOGLE_EXTENSION_APP_ID }}/publish"
      continue-on-error: true
